version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "3251"
      MYSQL_DATABASE: meeting_app
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./backend/infra/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./backend/infra/redis/data:/data # /data(redis) -> ./infra/redis/data(local) 저장
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

volumes:
  mysql_data: