/* tslint:disable */
/* eslint-disable */
/**
 * 4차 프로젝트 6팀 March API
 * 6팀 March의 백엔드 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddImagesRequest
 */
export interface AddImagesRequest {
    /**
     * 
     * @type {Array<Blob>}
     * @memberof AddImagesRequest
     */
    files: Array<Blob>;
}

/**
 * Check if a given object implements the AddImagesRequest interface.
 */
export function instanceOfAddImagesRequest(value: object): value is AddImagesRequest {
    if (!('files' in value) || value['files'] === undefined) return false;
    return true;
}

export function AddImagesRequestFromJSON(json: any): AddImagesRequest {
    return AddImagesRequestFromJSONTyped(json, false);
}

export function AddImagesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddImagesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'files': json['files'],
    };
}

export function AddImagesRequestToJSON(json: any): AddImagesRequest {
    return AddImagesRequestToJSONTyped(json, false);
}

export function AddImagesRequestToJSONTyped(value?: AddImagesRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'files': value['files'],
    };
}

