/* tslint:disable */
/* eslint-disable */
/**
 * 4차 프로젝트 6팀 March API
 * 6팀 March의 백엔드 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlockUserRequest
 */
export interface BlockUserRequest {
    /**
     * 
     * @type {number}
     * @memberof BlockUserRequest
     */
    blockedId?: number;
}

/**
 * Check if a given object implements the BlockUserRequest interface.
 */
export function instanceOfBlockUserRequest(value: object): value is BlockUserRequest {
    return true;
}

export function BlockUserRequestFromJSON(json: any): BlockUserRequest {
    return BlockUserRequestFromJSONTyped(json, false);
}

export function BlockUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'blockedId': json['blocked_id'] == null ? undefined : json['blocked_id'],
    };
}

export function BlockUserRequestToJSON(json: any): BlockUserRequest {
    return BlockUserRequestToJSONTyped(json, false);
}

export function BlockUserRequestToJSONTyped(value?: BlockUserRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'blocked_id': value['blockedId'],
    };
}

