/* tslint:disable */
/* eslint-disable */
/**
 * 4차 프로젝트 6팀 March API
 * 6팀 March의 백엔드 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlockedUserResponse
 */
export interface BlockedUserResponse {
    /**
     * 
     * @type {number}
     * @memberof BlockedUserResponse
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof BlockedUserResponse
     */
    nickname?: string;
    /**
     * 
     * @type {number}
     * @memberof BlockedUserResponse
     */
    age?: number;
    /**
     * 
     * @type {string}
     * @memberof BlockedUserResponse
     */
    gender?: string;
    /**
     * 
     * @type {Date}
     * @memberof BlockedUserResponse
     */
    blockedAt?: Date;
}

/**
 * Check if a given object implements the BlockedUserResponse interface.
 */
export function instanceOfBlockedUserResponse(value: object): value is BlockedUserResponse {
    return true;
}

export function BlockedUserResponseFromJSON(json: any): BlockedUserResponse {
    return BlockedUserResponseFromJSONTyped(json, false);
}

export function BlockedUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockedUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'nickname': json['nickname'] == null ? undefined : json['nickname'],
        'age': json['age'] == null ? undefined : json['age'],
        'gender': json['gender'] == null ? undefined : json['gender'],
        'blockedAt': json['blockedAt'] == null ? undefined : (new Date(json['blockedAt'])),
    };
}

export function BlockedUserResponseToJSON(json: any): BlockedUserResponse {
    return BlockedUserResponseToJSONTyped(json, false);
}

export function BlockedUserResponseToJSONTyped(value?: BlockedUserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'nickname': value['nickname'],
        'age': value['age'],
        'gender': value['gender'],
        'blockedAt': value['blockedAt'] == null ? undefined : ((value['blockedAt']).toISOString()),
    };
}

