/* tslint:disable */
/* eslint-disable */
/**
 * 4차 프로젝트 6팀 March API
 * 6팀 March의 백엔드 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatRoomResponse
 */
export interface ChatRoomResponse {
    /**
     * 
     * @type {number}
     * @memberof ChatRoomResponse
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof ChatRoomResponse
     */
    senderId?: number;
    /**
     * 
     * @type {number}
     * @memberof ChatRoomResponse
     */
    receiverId?: number;
    /**
     * 
     * @type {Date}
     * @memberof ChatRoomResponse
     */
    createdAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof ChatRoomResponse
     */
    unreadCount?: number;
    /**
     * 
     * @type {string}
     * @memberof ChatRoomResponse
     */
    opponentNickname?: string;
    /**
     * 
     * @type {string}
     * @memberof ChatRoomResponse
     */
    opponentProfileImgUrl?: string;
}

/**
 * Check if a given object implements the ChatRoomResponse interface.
 */
export function instanceOfChatRoomResponse(value: object): value is ChatRoomResponse {
    return true;
}

export function ChatRoomResponseFromJSON(json: any): ChatRoomResponse {
    return ChatRoomResponseFromJSONTyped(json, false);
}

export function ChatRoomResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatRoomResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'senderId': json['senderId'] == null ? undefined : json['senderId'],
        'receiverId': json['receiverId'] == null ? undefined : json['receiverId'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'unreadCount': json['unreadCount'] == null ? undefined : json['unreadCount'],
        'opponentNickname': json['opponentNickname'] == null ? undefined : json['opponentNickname'],
        'opponentProfileImgUrl': json['opponentProfileImgUrl'] == null ? undefined : json['opponentProfileImgUrl'],
    };
}

export function ChatRoomResponseToJSON(json: any): ChatRoomResponse {
    return ChatRoomResponseToJSONTyped(json, false);
}

export function ChatRoomResponseToJSONTyped(value?: ChatRoomResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'senderId': value['senderId'],
        'receiverId': value['receiverId'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'unreadCount': value['unreadCount'],
        'opponentNickname': value['opponentNickname'],
        'opponentProfileImgUrl': value['opponentProfileImgUrl'],
    };
}

