/* tslint:disable */
/* eslint-disable */
/**
 * 4차 프로젝트 6팀 March API
 * 6팀 March의 백엔드 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BlockedUserResponse } from './BlockedUserResponse';
import {
    BlockedUserResponseFromJSON,
    BlockedUserResponseFromJSONTyped,
    BlockedUserResponseToJSON,
    BlockedUserResponseToJSONTyped,
} from './BlockedUserResponse';

/**
 * 
 * @export
 * @interface GenericResponseListBlockedUserResponse
 */
export interface GenericResponseListBlockedUserResponse {
    /**
     * 
     * @type {Date}
     * @memberof GenericResponseListBlockedUserResponse
     */
    timestamp?: Date;
    /**
     * 
     * @type {number}
     * @memberof GenericResponseListBlockedUserResponse
     */
    code?: number;
    /**
     * 
     * @type {Array<BlockedUserResponse>}
     * @memberof GenericResponseListBlockedUserResponse
     */
    data?: Array<BlockedUserResponse>;
    /**
     * 
     * @type {string}
     * @memberof GenericResponseListBlockedUserResponse
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GenericResponseListBlockedUserResponse
     */
    isSuccess?: boolean;
}

/**
 * Check if a given object implements the GenericResponseListBlockedUserResponse interface.
 */
export function instanceOfGenericResponseListBlockedUserResponse(value: object): value is GenericResponseListBlockedUserResponse {
    return true;
}

export function GenericResponseListBlockedUserResponseFromJSON(json: any): GenericResponseListBlockedUserResponse {
    return GenericResponseListBlockedUserResponseFromJSONTyped(json, false);
}

export function GenericResponseListBlockedUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenericResponseListBlockedUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(BlockedUserResponseFromJSON)),
        'message': json['message'] == null ? undefined : json['message'],
        'isSuccess': json['isSuccess'] == null ? undefined : json['isSuccess'],
    };
}

export function GenericResponseListBlockedUserResponseToJSON(json: any): GenericResponseListBlockedUserResponse {
    return GenericResponseListBlockedUserResponseToJSONTyped(json, false);
}

export function GenericResponseListBlockedUserResponseToJSONTyped(value?: GenericResponseListBlockedUserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
        'code': value['code'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(BlockedUserResponseToJSON)),
        'message': value['message'],
        'isSuccess': value['isSuccess'],
    };
}

