/* tslint:disable */
/* eslint-disable */
/**
 * 4차 프로젝트 6팀 March API
 * 6팀 March의 백엔드 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenericResponseVoid
 */
export interface GenericResponseVoid {
    /**
     * 
     * @type {Date}
     * @memberof GenericResponseVoid
     */
    timestamp?: Date;
    /**
     * 
     * @type {number}
     * @memberof GenericResponseVoid
     */
    code?: number;
    /**
     * 
     * @type {object}
     * @memberof GenericResponseVoid
     */
    data?: object;
    /**
     * 
     * @type {string}
     * @memberof GenericResponseVoid
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GenericResponseVoid
     */
    isSuccess?: boolean;
}

/**
 * Check if a given object implements the GenericResponseVoid interface.
 */
export function instanceOfGenericResponseVoid(value: object): value is GenericResponseVoid {
    return true;
}

export function GenericResponseVoidFromJSON(json: any): GenericResponseVoid {
    return GenericResponseVoidFromJSONTyped(json, false);
}

export function GenericResponseVoidFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenericResponseVoid {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : json['data'],
        'message': json['message'] == null ? undefined : json['message'],
        'isSuccess': json['isSuccess'] == null ? undefined : json['isSuccess'],
    };
}

export function GenericResponseVoidToJSON(json: any): GenericResponseVoid {
    return GenericResponseVoidToJSONTyped(json, false);
}

export function GenericResponseVoidToJSONTyped(value?: GenericResponseVoid | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
        'code': value['code'],
        'data': value['data'],
        'message': value['message'],
        'isSuccess': value['isSuccess'],
    };
}

