/* tslint:disable */
/* eslint-disable */
/**
 * 4차 프로젝트 6팀 March API
 * 6팀 March의 백엔드 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SliceChatMessageResponse } from './SliceChatMessageResponse';
import {
    SliceChatMessageResponseFromJSON,
    SliceChatMessageResponseFromJSONTyped,
    SliceChatMessageResponseToJSON,
    SliceChatMessageResponseToJSONTyped,
} from './SliceChatMessageResponse';

/**
 * 
 * @export
 * @interface GenericResponseSliceChatMessageResponse
 */
export interface GenericResponseSliceChatMessageResponse {
    /**
     * 
     * @type {Date}
     * @memberof GenericResponseSliceChatMessageResponse
     */
    timestamp?: Date;
    /**
     * 
     * @type {number}
     * @memberof GenericResponseSliceChatMessageResponse
     */
    code?: number;
    /**
     * 
     * @type {SliceChatMessageResponse}
     * @memberof GenericResponseSliceChatMessageResponse
     */
    data?: SliceChatMessageResponse;
    /**
     * 
     * @type {string}
     * @memberof GenericResponseSliceChatMessageResponse
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GenericResponseSliceChatMessageResponse
     */
    isSuccess?: boolean;
}

/**
 * Check if a given object implements the GenericResponseSliceChatMessageResponse interface.
 */
export function instanceOfGenericResponseSliceChatMessageResponse(value: object): value is GenericResponseSliceChatMessageResponse {
    return true;
}

export function GenericResponseSliceChatMessageResponseFromJSON(json: any): GenericResponseSliceChatMessageResponse {
    return GenericResponseSliceChatMessageResponseFromJSONTyped(json, false);
}

export function GenericResponseSliceChatMessageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenericResponseSliceChatMessageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : SliceChatMessageResponseFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'isSuccess': json['isSuccess'] == null ? undefined : json['isSuccess'],
    };
}

export function GenericResponseSliceChatMessageResponseToJSON(json: any): GenericResponseSliceChatMessageResponse {
    return GenericResponseSliceChatMessageResponseToJSONTyped(json, false);
}

export function GenericResponseSliceChatMessageResponseToJSONTyped(value?: GenericResponseSliceChatMessageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
        'code': value['code'],
        'data': SliceChatMessageResponseToJSON(value['data']),
        'message': value['message'],
        'isSuccess': value['isSuccess'],
    };
}

