/* tslint:disable */
/* eslint-disable */
/**
 * 4차 프로젝트 6팀 March API
 * 6팀 March의 백엔드 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageChatRoomResponse } from './PageChatRoomResponse';
import {
    PageChatRoomResponseFromJSON,
    PageChatRoomResponseFromJSONTyped,
    PageChatRoomResponseToJSON,
    PageChatRoomResponseToJSONTyped,
} from './PageChatRoomResponse';

/**
 * 
 * @export
 * @interface GenericResponsePageChatRoomResponse
 */
export interface GenericResponsePageChatRoomResponse {
    /**
     * 
     * @type {Date}
     * @memberof GenericResponsePageChatRoomResponse
     */
    timestamp?: Date;
    /**
     * 
     * @type {number}
     * @memberof GenericResponsePageChatRoomResponse
     */
    code?: number;
    /**
     * 
     * @type {PageChatRoomResponse}
     * @memberof GenericResponsePageChatRoomResponse
     */
    data?: PageChatRoomResponse;
    /**
     * 
     * @type {string}
     * @memberof GenericResponsePageChatRoomResponse
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GenericResponsePageChatRoomResponse
     */
    isSuccess?: boolean;
}

/**
 * Check if a given object implements the GenericResponsePageChatRoomResponse interface.
 */
export function instanceOfGenericResponsePageChatRoomResponse(value: object): value is GenericResponsePageChatRoomResponse {
    return true;
}

export function GenericResponsePageChatRoomResponseFromJSON(json: any): GenericResponsePageChatRoomResponse {
    return GenericResponsePageChatRoomResponseFromJSONTyped(json, false);
}

export function GenericResponsePageChatRoomResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenericResponsePageChatRoomResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : PageChatRoomResponseFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'isSuccess': json['isSuccess'] == null ? undefined : json['isSuccess'],
    };
}

export function GenericResponsePageChatRoomResponseToJSON(json: any): GenericResponsePageChatRoomResponse {
    return GenericResponsePageChatRoomResponseToJSONTyped(json, false);
}

export function GenericResponsePageChatRoomResponseToJSONTyped(value?: GenericResponsePageChatRoomResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
        'code': value['code'],
        'data': PageChatRoomResponseToJSON(value['data']),
        'message': value['message'],
        'isSuccess': value['isSuccess'],
    };
}

