/* tslint:disable */
/* eslint-disable */
/**
 * 4차 프로젝트 6팀 March API
 * 6팀 March의 백엔드 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MemberResponseDto } from './MemberResponseDto';
import {
    MemberResponseDtoFromJSON,
    MemberResponseDtoFromJSONTyped,
    MemberResponseDtoToJSON,
    MemberResponseDtoToJSONTyped,
} from './MemberResponseDto';

/**
 * 
 * @export
 * @interface GenericResponseListMemberResponseDto
 */
export interface GenericResponseListMemberResponseDto {
    /**
     * 
     * @type {Date}
     * @memberof GenericResponseListMemberResponseDto
     */
    timestamp?: Date;
    /**
     * 
     * @type {number}
     * @memberof GenericResponseListMemberResponseDto
     */
    code?: number;
    /**
     * 
     * @type {Array<MemberResponseDto>}
     * @memberof GenericResponseListMemberResponseDto
     */
    data?: Array<MemberResponseDto>;
    /**
     * 
     * @type {string}
     * @memberof GenericResponseListMemberResponseDto
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GenericResponseListMemberResponseDto
     */
    isSuccess?: boolean;
}

/**
 * Check if a given object implements the GenericResponseListMemberResponseDto interface.
 */
export function instanceOfGenericResponseListMemberResponseDto(value: object): value is GenericResponseListMemberResponseDto {
    return true;
}

export function GenericResponseListMemberResponseDtoFromJSON(json: any): GenericResponseListMemberResponseDto {
    return GenericResponseListMemberResponseDtoFromJSONTyped(json, false);
}

export function GenericResponseListMemberResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenericResponseListMemberResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(MemberResponseDtoFromJSON)),
        'message': json['message'] == null ? undefined : json['message'],
        'isSuccess': json['isSuccess'] == null ? undefined : json['isSuccess'],
    };
}

export function GenericResponseListMemberResponseDtoToJSON(json: any): GenericResponseListMemberResponseDto {
    return GenericResponseListMemberResponseDtoToJSONTyped(json, false);
}

export function GenericResponseListMemberResponseDtoToJSONTyped(value?: GenericResponseListMemberResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
        'code': value['code'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(MemberResponseDtoToJSON)),
        'message': value['message'],
        'isSuccess': value['isSuccess'],
    };
}

