/* tslint:disable */
/* eslint-disable */
/**
 * 4차 프로젝트 6팀 March API
 * 6팀 March의 백엔드 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatRequestDto } from './ChatRequestDto';
import {
    ChatRequestDtoFromJSON,
    ChatRequestDtoFromJSONTyped,
    ChatRequestDtoToJSON,
    ChatRequestDtoToJSONTyped,
} from './ChatRequestDto';

/**
 * 
 * @export
 * @interface GenericResponseListChatRequestDto
 */
export interface GenericResponseListChatRequestDto {
    /**
     * 
     * @type {Date}
     * @memberof GenericResponseListChatRequestDto
     */
    timestamp?: Date;
    /**
     * 
     * @type {number}
     * @memberof GenericResponseListChatRequestDto
     */
    code?: number;
    /**
     * 
     * @type {Array<ChatRequestDto>}
     * @memberof GenericResponseListChatRequestDto
     */
    data?: Array<ChatRequestDto>;
    /**
     * 
     * @type {string}
     * @memberof GenericResponseListChatRequestDto
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GenericResponseListChatRequestDto
     */
    isSuccess?: boolean;
}

/**
 * Check if a given object implements the GenericResponseListChatRequestDto interface.
 */
export function instanceOfGenericResponseListChatRequestDto(value: object): value is GenericResponseListChatRequestDto {
    return true;
}

export function GenericResponseListChatRequestDtoFromJSON(json: any): GenericResponseListChatRequestDto {
    return GenericResponseListChatRequestDtoFromJSONTyped(json, false);
}

export function GenericResponseListChatRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenericResponseListChatRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ChatRequestDtoFromJSON)),
        'message': json['message'] == null ? undefined : json['message'],
        'isSuccess': json['isSuccess'] == null ? undefined : json['isSuccess'],
    };
}

export function GenericResponseListChatRequestDtoToJSON(json: any): GenericResponseListChatRequestDto {
    return GenericResponseListChatRequestDtoToJSONTyped(json, false);
}

export function GenericResponseListChatRequestDtoToJSONTyped(value?: GenericResponseListChatRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
        'code': value['code'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ChatRequestDtoToJSON)),
        'message': value['message'],
        'isSuccess': value['isSuccess'],
    };
}

