/* tslint:disable */
/* eslint-disable */
/**
 * 4차 프로젝트 6팀 March API
 * 6팀 March의 백엔드 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LoginResponseDto } from './LoginResponseDto';
import {
    LoginResponseDtoFromJSON,
    LoginResponseDtoFromJSONTyped,
    LoginResponseDtoToJSON,
    LoginResponseDtoToJSONTyped,
} from './LoginResponseDto';

/**
 * 
 * @export
 * @interface GenericResponseLoginResponseDto
 */
export interface GenericResponseLoginResponseDto {
    /**
     * 
     * @type {Date}
     * @memberof GenericResponseLoginResponseDto
     */
    timestamp?: Date;
    /**
     * 
     * @type {number}
     * @memberof GenericResponseLoginResponseDto
     */
    code?: number;
    /**
     * 
     * @type {LoginResponseDto}
     * @memberof GenericResponseLoginResponseDto
     */
    data?: LoginResponseDto;
    /**
     * 
     * @type {string}
     * @memberof GenericResponseLoginResponseDto
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GenericResponseLoginResponseDto
     */
    isSuccess?: boolean;
}

/**
 * Check if a given object implements the GenericResponseLoginResponseDto interface.
 */
export function instanceOfGenericResponseLoginResponseDto(value: object): value is GenericResponseLoginResponseDto {
    return true;
}

export function GenericResponseLoginResponseDtoFromJSON(json: any): GenericResponseLoginResponseDto {
    return GenericResponseLoginResponseDtoFromJSONTyped(json, false);
}

export function GenericResponseLoginResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenericResponseLoginResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : LoginResponseDtoFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'isSuccess': json['isSuccess'] == null ? undefined : json['isSuccess'],
    };
}

export function GenericResponseLoginResponseDtoToJSON(json: any): GenericResponseLoginResponseDto {
    return GenericResponseLoginResponseDtoToJSONTyped(json, false);
}

export function GenericResponseLoginResponseDtoToJSONTyped(value?: GenericResponseLoginResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
        'code': value['code'],
        'data': LoginResponseDtoToJSON(value['data']),
        'message': value['message'],
        'isSuccess': value['isSuccess'],
    };
}

