/* tslint:disable */
/* eslint-disable */
/**
 * 4차 프로젝트 6팀 March API
 * 6팀 March의 백엔드 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenericResponseBoolean
 */
export interface GenericResponseBoolean {
    /**
     * 
     * @type {Date}
     * @memberof GenericResponseBoolean
     */
    timestamp?: Date;
    /**
     * 
     * @type {number}
     * @memberof GenericResponseBoolean
     */
    code?: number;
    /**
     * 
     * @type {boolean}
     * @memberof GenericResponseBoolean
     */
    data?: boolean;
    /**
     * 
     * @type {string}
     * @memberof GenericResponseBoolean
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GenericResponseBoolean
     */
    isSuccess?: boolean;
}

/**
 * Check if a given object implements the GenericResponseBoolean interface.
 */
export function instanceOfGenericResponseBoolean(value: object): value is GenericResponseBoolean {
    return true;
}

export function GenericResponseBooleanFromJSON(json: any): GenericResponseBoolean {
    return GenericResponseBooleanFromJSONTyped(json, false);
}

export function GenericResponseBooleanFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenericResponseBoolean {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : json['data'],
        'message': json['message'] == null ? undefined : json['message'],
        'isSuccess': json['isSuccess'] == null ? undefined : json['isSuccess'],
    };
}

export function GenericResponseBooleanToJSON(json: any): GenericResponseBoolean {
    return GenericResponseBooleanToJSONTyped(json, false);
}

export function GenericResponseBooleanToJSONTyped(value?: GenericResponseBoolean | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
        'code': value['code'],
        'data': value['data'],
        'message': value['message'],
        'isSuccess': value['isSuccess'],
    };
}

