/* tslint:disable */
/* eslint-disable */
/**
 * 4차 프로젝트 6팀 March API
 * 6팀 March의 백엔드 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenericResponseString
 */
export interface GenericResponseString {
    /**
     * 
     * @type {Date}
     * @memberof GenericResponseString
     */
    timestamp?: Date;
    /**
     * 
     * @type {number}
     * @memberof GenericResponseString
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof GenericResponseString
     */
    data?: string;
    /**
     * 
     * @type {string}
     * @memberof GenericResponseString
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GenericResponseString
     */
    isSuccess?: boolean;
}

/**
 * Check if a given object implements the GenericResponseString interface.
 */
export function instanceOfGenericResponseString(value: object): value is GenericResponseString {
    return true;
}

export function GenericResponseStringFromJSON(json: any): GenericResponseString {
    return GenericResponseStringFromJSONTyped(json, false);
}

export function GenericResponseStringFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenericResponseString {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : json['data'],
        'message': json['message'] == null ? undefined : json['message'],
        'isSuccess': json['isSuccess'] == null ? undefined : json['isSuccess'],
    };
}

export function GenericResponseStringToJSON(json: any): GenericResponseString {
    return GenericResponseStringToJSONTyped(json, false);
}

export function GenericResponseStringToJSONTyped(value?: GenericResponseString | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
        'code': value['code'],
        'data': value['data'],
        'message': value['message'],
        'isSuccess': value['isSuccess'],
    };
}

