/* tslint:disable */
/* eslint-disable */
/**
 * 4차 프로젝트 6팀 March API
 * 6팀 March의 백엔드 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { KeywordCategoryResponse } from './KeywordCategoryResponse';
import {
    KeywordCategoryResponseFromJSON,
    KeywordCategoryResponseFromJSONTyped,
    KeywordCategoryResponseToJSON,
    KeywordCategoryResponseToJSONTyped,
} from './KeywordCategoryResponse';

/**
 * 
 * @export
 * @interface GenericResponseListKeywordCategoryResponse
 */
export interface GenericResponseListKeywordCategoryResponse {
    /**
     * 
     * @type {Date}
     * @memberof GenericResponseListKeywordCategoryResponse
     */
    timestamp?: Date;
    /**
     * 
     * @type {number}
     * @memberof GenericResponseListKeywordCategoryResponse
     */
    code?: number;
    /**
     * 
     * @type {Array<KeywordCategoryResponse>}
     * @memberof GenericResponseListKeywordCategoryResponse
     */
    data?: Array<KeywordCategoryResponse>;
    /**
     * 
     * @type {string}
     * @memberof GenericResponseListKeywordCategoryResponse
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GenericResponseListKeywordCategoryResponse
     */
    isSuccess?: boolean;
}

/**
 * Check if a given object implements the GenericResponseListKeywordCategoryResponse interface.
 */
export function instanceOfGenericResponseListKeywordCategoryResponse(value: object): value is GenericResponseListKeywordCategoryResponse {
    return true;
}

export function GenericResponseListKeywordCategoryResponseFromJSON(json: any): GenericResponseListKeywordCategoryResponse {
    return GenericResponseListKeywordCategoryResponseFromJSONTyped(json, false);
}

export function GenericResponseListKeywordCategoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenericResponseListKeywordCategoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(KeywordCategoryResponseFromJSON)),
        'message': json['message'] == null ? undefined : json['message'],
        'isSuccess': json['isSuccess'] == null ? undefined : json['isSuccess'],
    };
}

export function GenericResponseListKeywordCategoryResponseToJSON(json: any): GenericResponseListKeywordCategoryResponse {
    return GenericResponseListKeywordCategoryResponseToJSONTyped(json, false);
}

export function GenericResponseListKeywordCategoryResponseToJSONTyped(value?: GenericResponseListKeywordCategoryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
        'code': value['code'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(KeywordCategoryResponseToJSON)),
        'message': value['message'],
        'isSuccess': value['isSuccess'],
    };
}

