/* tslint:disable */
/* eslint-disable */
/**
 * 4차 프로젝트 6팀 March API
 * 6팀 March의 백엔드 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NotificationDto } from './NotificationDto';
import {
    NotificationDtoFromJSON,
    NotificationDtoFromJSONTyped,
    NotificationDtoToJSON,
    NotificationDtoToJSONTyped,
} from './NotificationDto';

/**
 * 
 * @export
 * @interface GenericResponseListNotificationDto
 */
export interface GenericResponseListNotificationDto {
    /**
     * 
     * @type {Date}
     * @memberof GenericResponseListNotificationDto
     */
    timestamp?: Date;
    /**
     * 
     * @type {number}
     * @memberof GenericResponseListNotificationDto
     */
    code?: number;
    /**
     * 
     * @type {Array<NotificationDto>}
     * @memberof GenericResponseListNotificationDto
     */
    data?: Array<NotificationDto>;
    /**
     * 
     * @type {string}
     * @memberof GenericResponseListNotificationDto
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GenericResponseListNotificationDto
     */
    isSuccess?: boolean;
}

/**
 * Check if a given object implements the GenericResponseListNotificationDto interface.
 */
export function instanceOfGenericResponseListNotificationDto(value: object): value is GenericResponseListNotificationDto {
    return true;
}

export function GenericResponseListNotificationDtoFromJSON(json: any): GenericResponseListNotificationDto {
    return GenericResponseListNotificationDtoFromJSONTyped(json, false);
}

export function GenericResponseListNotificationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenericResponseListNotificationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(NotificationDtoFromJSON)),
        'message': json['message'] == null ? undefined : json['message'],
        'isSuccess': json['isSuccess'] == null ? undefined : json['isSuccess'],
    };
}

export function GenericResponseListNotificationDtoToJSON(json: any): GenericResponseListNotificationDto {
    return GenericResponseListNotificationDtoToJSONTyped(json, false);
}

export function GenericResponseListNotificationDtoToJSONTyped(value?: GenericResponseListNotificationDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
        'code': value['code'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(NotificationDtoToJSON)),
        'message': value['message'],
        'isSuccess': value['isSuccess'],
    };
}

