/* tslint:disable */
/* eslint-disable */
/**
 * 4차 프로젝트 6팀 March API
 * 6팀 March의 백엔드 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MemberResponseDto } from './MemberResponseDto';
import {
    MemberResponseDtoFromJSON,
    MemberResponseDtoFromJSONTyped,
    MemberResponseDtoToJSON,
    MemberResponseDtoToJSONTyped,
} from './MemberResponseDto';

/**
 * 
 * @export
 * @interface GenericResponseMemberResponseDto
 */
export interface GenericResponseMemberResponseDto {
    /**
     * 
     * @type {Date}
     * @memberof GenericResponseMemberResponseDto
     */
    timestamp?: Date;
    /**
     * 
     * @type {number}
     * @memberof GenericResponseMemberResponseDto
     */
    code?: number;
    /**
     * 
     * @type {MemberResponseDto}
     * @memberof GenericResponseMemberResponseDto
     */
    data?: MemberResponseDto;
    /**
     * 
     * @type {string}
     * @memberof GenericResponseMemberResponseDto
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GenericResponseMemberResponseDto
     */
    isSuccess?: boolean;
}

/**
 * Check if a given object implements the GenericResponseMemberResponseDto interface.
 */
export function instanceOfGenericResponseMemberResponseDto(value: object): value is GenericResponseMemberResponseDto {
    return true;
}

export function GenericResponseMemberResponseDtoFromJSON(json: any): GenericResponseMemberResponseDto {
    return GenericResponseMemberResponseDtoFromJSONTyped(json, false);
}

export function GenericResponseMemberResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenericResponseMemberResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : MemberResponseDtoFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'isSuccess': json['isSuccess'] == null ? undefined : json['isSuccess'],
    };
}

export function GenericResponseMemberResponseDtoToJSON(json: any): GenericResponseMemberResponseDto {
    return GenericResponseMemberResponseDtoToJSONTyped(json, false);
}

export function GenericResponseMemberResponseDtoToJSONTyped(value?: GenericResponseMemberResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
        'code': value['code'],
        'data': MemberResponseDtoToJSON(value['data']),
        'message': value['message'],
        'isSuccess': value['isSuccess'],
    };
}

