/* tslint:disable */
/* eslint-disable */
/**
 * 4차 프로젝트 6팀 March API
 * 6팀 March의 백엔드 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MemberRegisterResponseDto } from './MemberRegisterResponseDto';
import {
    MemberRegisterResponseDtoFromJSON,
    MemberRegisterResponseDtoFromJSONTyped,
    MemberRegisterResponseDtoToJSON,
    MemberRegisterResponseDtoToJSONTyped,
} from './MemberRegisterResponseDto';

/**
 * 
 * @export
 * @interface GenericResponseMemberRegisterResponseDto
 */
export interface GenericResponseMemberRegisterResponseDto {
    /**
     * 
     * @type {Date}
     * @memberof GenericResponseMemberRegisterResponseDto
     */
    timestamp?: Date;
    /**
     * 
     * @type {number}
     * @memberof GenericResponseMemberRegisterResponseDto
     */
    code?: number;
    /**
     * 
     * @type {MemberRegisterResponseDto}
     * @memberof GenericResponseMemberRegisterResponseDto
     */
    data?: MemberRegisterResponseDto;
    /**
     * 
     * @type {string}
     * @memberof GenericResponseMemberRegisterResponseDto
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GenericResponseMemberRegisterResponseDto
     */
    isSuccess?: boolean;
}

/**
 * Check if a given object implements the GenericResponseMemberRegisterResponseDto interface.
 */
export function instanceOfGenericResponseMemberRegisterResponseDto(value: object): value is GenericResponseMemberRegisterResponseDto {
    return true;
}

export function GenericResponseMemberRegisterResponseDtoFromJSON(json: any): GenericResponseMemberRegisterResponseDto {
    return GenericResponseMemberRegisterResponseDtoFromJSONTyped(json, false);
}

export function GenericResponseMemberRegisterResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenericResponseMemberRegisterResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : MemberRegisterResponseDtoFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'isSuccess': json['isSuccess'] == null ? undefined : json['isSuccess'],
    };
}

export function GenericResponseMemberRegisterResponseDtoToJSON(json: any): GenericResponseMemberRegisterResponseDto {
    return GenericResponseMemberRegisterResponseDtoToJSONTyped(json, false);
}

export function GenericResponseMemberRegisterResponseDtoToJSONTyped(value?: GenericResponseMemberRegisterResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
        'code': value['code'],
        'data': MemberRegisterResponseDtoToJSON(value['data']),
        'message': value['message'],
        'isSuccess': value['isSuccess'],
    };
}

