/* tslint:disable */
/* eslint-disable */
/**
 * 4차 프로젝트 6팀 March API
 * 6팀 March의 백엔드 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecommendedUserDto } from './RecommendedUserDto';
import {
    RecommendedUserDtoFromJSON,
    RecommendedUserDtoFromJSONTyped,
    RecommendedUserDtoToJSON,
    RecommendedUserDtoToJSONTyped,
} from './RecommendedUserDto';

/**
 * 
 * @export
 * @interface GenericResponseListRecommendedUserDto
 */
export interface GenericResponseListRecommendedUserDto {
    /**
     * 
     * @type {Date}
     * @memberof GenericResponseListRecommendedUserDto
     */
    timestamp?: Date;
    /**
     * 
     * @type {number}
     * @memberof GenericResponseListRecommendedUserDto
     */
    code?: number;
    /**
     * 
     * @type {Array<RecommendedUserDto>}
     * @memberof GenericResponseListRecommendedUserDto
     */
    data?: Array<RecommendedUserDto>;
    /**
     * 
     * @type {string}
     * @memberof GenericResponseListRecommendedUserDto
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GenericResponseListRecommendedUserDto
     */
    isSuccess?: boolean;
}

/**
 * Check if a given object implements the GenericResponseListRecommendedUserDto interface.
 */
export function instanceOfGenericResponseListRecommendedUserDto(value: object): value is GenericResponseListRecommendedUserDto {
    return true;
}

export function GenericResponseListRecommendedUserDtoFromJSON(json: any): GenericResponseListRecommendedUserDto {
    return GenericResponseListRecommendedUserDtoFromJSONTyped(json, false);
}

export function GenericResponseListRecommendedUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenericResponseListRecommendedUserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(RecommendedUserDtoFromJSON)),
        'message': json['message'] == null ? undefined : json['message'],
        'isSuccess': json['isSuccess'] == null ? undefined : json['isSuccess'],
    };
}

export function GenericResponseListRecommendedUserDtoToJSON(json: any): GenericResponseListRecommendedUserDto {
    return GenericResponseListRecommendedUserDtoToJSONTyped(json, false);
}

export function GenericResponseListRecommendedUserDtoToJSONTyped(value?: GenericResponseListRecommendedUserDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
        'code': value['code'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(RecommendedUserDtoToJSON)),
        'message': value['message'],
        'isSuccess': value['isSuccess'],
    };
}

