/* tslint:disable */
/* eslint-disable */
/**
 * 4차 프로젝트 6팀 March API
 * 6팀 March의 백엔드 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImageResponseDto } from './ImageResponseDto';
import {
    ImageResponseDtoFromJSON,
    ImageResponseDtoFromJSONTyped,
    ImageResponseDtoToJSON,
    ImageResponseDtoToJSONTyped,
} from './ImageResponseDto';

/**
 * 
 * @export
 * @interface GenericResponseListImageResponseDto
 */
export interface GenericResponseListImageResponseDto {
    /**
     * 
     * @type {Date}
     * @memberof GenericResponseListImageResponseDto
     */
    timestamp?: Date;
    /**
     * 
     * @type {number}
     * @memberof GenericResponseListImageResponseDto
     */
    code?: number;
    /**
     * 
     * @type {Array<ImageResponseDto>}
     * @memberof GenericResponseListImageResponseDto
     */
    data?: Array<ImageResponseDto>;
    /**
     * 
     * @type {string}
     * @memberof GenericResponseListImageResponseDto
     */
    message?: string;
    /**
     * 
     * @type {boolean}
     * @memberof GenericResponseListImageResponseDto
     */
    isSuccess?: boolean;
}

/**
 * Check if a given object implements the GenericResponseListImageResponseDto interface.
 */
export function instanceOfGenericResponseListImageResponseDto(value: object): value is GenericResponseListImageResponseDto {
    return true;
}

export function GenericResponseListImageResponseDtoFromJSON(json: any): GenericResponseListImageResponseDto {
    return GenericResponseListImageResponseDtoFromJSONTyped(json, false);
}

export function GenericResponseListImageResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenericResponseListImageResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ImageResponseDtoFromJSON)),
        'message': json['message'] == null ? undefined : json['message'],
        'isSuccess': json['isSuccess'] == null ? undefined : json['isSuccess'],
    };
}

export function GenericResponseListImageResponseDtoToJSON(json: any): GenericResponseListImageResponseDto {
    return GenericResponseListImageResponseDtoToJSONTyped(json, false);
}

export function GenericResponseListImageResponseDtoToJSONTyped(value?: GenericResponseListImageResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
        'code': value['code'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ImageResponseDtoToJSON)),
        'message': value['message'],
        'isSuccess': value['isSuccess'],
    };
}

