/* tslint:disable */
/* eslint-disable */
/**
 * 4차 프로젝트 6팀 March API
 * 6팀 March의 백엔드 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImageResponseDto
 */
export interface ImageResponseDto {
    /**
     * 
     * @type {number}
     * @memberof ImageResponseDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ImageResponseDto
     */
    url?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ImageResponseDto
     */
    isPrimary?: boolean;
}

/**
 * Check if a given object implements the ImageResponseDto interface.
 */
export function instanceOfImageResponseDto(value: object): value is ImageResponseDto {
    return true;
}

export function ImageResponseDtoFromJSON(json: any): ImageResponseDto {
    return ImageResponseDtoFromJSONTyped(json, false);
}

export function ImageResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'url': json['url'] == null ? undefined : json['url'],
        'isPrimary': json['isPrimary'] == null ? undefined : json['isPrimary'],
    };
}

export function ImageResponseDtoToJSON(json: any): ImageResponseDto {
    return ImageResponseDtoToJSONTyped(json, false);
}

export function ImageResponseDtoToJSONTyped(value?: ImageResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'url': value['url'],
        'isPrimary': value['isPrimary'],
    };
}

