/* tslint:disable */
/* eslint-disable */
/**
 * 4차 프로젝트 6팀 March API
 * 6팀 March의 백엔드 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KeywordResponse
 */
export interface KeywordResponse {
    /**
     * 
     * @type {number}
     * @memberof KeywordResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof KeywordResponse
     */
    name?: string;
}

/**
 * Check if a given object implements the KeywordResponse interface.
 */
export function instanceOfKeywordResponse(value: object): value is KeywordResponse {
    return true;
}

export function KeywordResponseFromJSON(json: any): KeywordResponse {
    return KeywordResponseFromJSONTyped(json, false);
}

export function KeywordResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): KeywordResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function KeywordResponseToJSON(json: any): KeywordResponse {
    return KeywordResponseToJSONTyped(json, false);
}

export function KeywordResponseToJSONTyped(value?: KeywordResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

