/* tslint:disable */
/* eslint-disable */
/**
 * 4차 프로젝트 6팀 March API
 * 6팀 March의 백엔드 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProfileImageDto } from './ProfileImageDto';
import {
    ProfileImageDtoFromJSON,
    ProfileImageDtoFromJSONTyped,
    ProfileImageDtoToJSON,
    ProfileImageDtoToJSONTyped,
} from './ProfileImageDto';

/**
 * 
 * @export
 * @interface LikeMemberProfileDto
 */
export interface LikeMemberProfileDto {
    /**
     * 
     * @type {number}
     * @memberof LikeMemberProfileDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof LikeMemberProfileDto
     */
    nickname?: string;
    /**
     * 
     * @type {ProfileImageDto}
     * @memberof LikeMemberProfileDto
     */
    profileImage?: ProfileImageDto;
}

/**
 * Check if a given object implements the LikeMemberProfileDto interface.
 */
export function instanceOfLikeMemberProfileDto(value: object): value is LikeMemberProfileDto {
    return true;
}

export function LikeMemberProfileDtoFromJSON(json: any): LikeMemberProfileDto {
    return LikeMemberProfileDtoFromJSONTyped(json, false);
}

export function LikeMemberProfileDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LikeMemberProfileDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'nickname': json['nickname'] == null ? undefined : json['nickname'],
        'profileImage': json['profileImage'] == null ? undefined : ProfileImageDtoFromJSON(json['profileImage']),
    };
}

export function LikeMemberProfileDtoToJSON(json: any): LikeMemberProfileDto {
    return LikeMemberProfileDtoToJSONTyped(json, false);
}

export function LikeMemberProfileDtoToJSONTyped(value?: LikeMemberProfileDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'nickname': value['nickname'],
        'profileImage': ProfileImageDtoToJSON(value['profileImage']),
    };
}

