/* tslint:disable */
/* eslint-disable */
/**
 * 4차 프로젝트 6팀 March API
 * 6팀 March의 백엔드 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MemberInfoDto } from './MemberInfoDto';
import {
    MemberInfoDtoFromJSON,
    MemberInfoDtoFromJSONTyped,
    MemberInfoDtoToJSON,
    MemberInfoDtoToJSONTyped,
} from './MemberInfoDto';

/**
 * 
 * @export
 * @interface MemberRegisterResponseDto
 */
export interface MemberRegisterResponseDto {
    /**
     * 
     * @type {MemberInfoDto}
     * @memberof MemberRegisterResponseDto
     */
    member?: MemberInfoDto;
    /**
     * 
     * @type {string}
     * @memberof MemberRegisterResponseDto
     */
    accessToken?: string;
    /**
     * 
     * @type {string}
     * @memberof MemberRegisterResponseDto
     */
    refreshToken?: string;
}

/**
 * Check if a given object implements the MemberRegisterResponseDto interface.
 */
export function instanceOfMemberRegisterResponseDto(value: object): value is MemberRegisterResponseDto {
    return true;
}

export function MemberRegisterResponseDtoFromJSON(json: any): MemberRegisterResponseDto {
    return MemberRegisterResponseDtoFromJSONTyped(json, false);
}

export function MemberRegisterResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberRegisterResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'member': json['member'] == null ? undefined : MemberInfoDtoFromJSON(json['member']),
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'refreshToken': json['refreshToken'] == null ? undefined : json['refreshToken'],
    };
}

export function MemberRegisterResponseDtoToJSON(json: any): MemberRegisterResponseDto {
    return MemberRegisterResponseDtoToJSONTyped(json, false);
}

export function MemberRegisterResponseDtoToJSONTyped(value?: MemberRegisterResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'member': MemberInfoDtoToJSON(value['member']),
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
    };
}

