/* tslint:disable */
/* eslint-disable */
/**
 * 4차 프로젝트 6팀 March API
 * 6팀 March의 백엔드 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImageResponseDto } from './ImageResponseDto';
import {
    ImageResponseDtoFromJSON,
    ImageResponseDtoFromJSONTyped,
    ImageResponseDtoToJSON,
    ImageResponseDtoToJSONTyped,
} from './ImageResponseDto';

/**
 * 
 * @export
 * @interface MemberResponseDto
 */
export interface MemberResponseDto {
    /**
     * 
     * @type {number}
     * @memberof MemberResponseDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof MemberResponseDto
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof MemberResponseDto
     */
    nickname?: string;
    /**
     * 
     * @type {string}
     * @memberof MemberResponseDto
     */
    gender?: string;
    /**
     * 
     * @type {number}
     * @memberof MemberResponseDto
     */
    age?: number;
    /**
     * 
     * @type {number}
     * @memberof MemberResponseDto
     */
    height?: number;
    /**
     * 
     * @type {ImageResponseDto}
     * @memberof MemberResponseDto
     */
    profileImage?: ImageResponseDto;
    /**
     * 
     * @type {Array<ImageResponseDto>}
     * @memberof MemberResponseDto
     */
    images?: Array<ImageResponseDto>;
    /**
     * 
     * @type {number}
     * @memberof MemberResponseDto
     */
    latitude?: number;
    /**
     * 
     * @type {number}
     * @memberof MemberResponseDto
     */
    longitude?: number;
}

/**
 * Check if a given object implements the MemberResponseDto interface.
 */
export function instanceOfMemberResponseDto(value: object): value is MemberResponseDto {
    return true;
}

export function MemberResponseDtoFromJSON(json: any): MemberResponseDto {
    return MemberResponseDtoFromJSONTyped(json, false);
}

export function MemberResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'email': json['email'] == null ? undefined : json['email'],
        'nickname': json['nickname'] == null ? undefined : json['nickname'],
        'gender': json['gender'] == null ? undefined : json['gender'],
        'age': json['age'] == null ? undefined : json['age'],
        'height': json['height'] == null ? undefined : json['height'],
        'profileImage': json['profileImage'] == null ? undefined : ImageResponseDtoFromJSON(json['profileImage']),
        'images': json['images'] == null ? undefined : ((json['images'] as Array<any>).map(ImageResponseDtoFromJSON)),
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
    };
}

export function MemberResponseDtoToJSON(json: any): MemberResponseDto {
    return MemberResponseDtoToJSONTyped(json, false);
}

export function MemberResponseDtoToJSONTyped(value?: MemberResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': value['email'],
        'nickname': value['nickname'],
        'gender': value['gender'],
        'age': value['age'],
        'height': value['height'],
        'profileImage': ImageResponseDtoToJSON(value['profileImage']),
        'images': value['images'] == null ? undefined : ((value['images'] as Array<any>).map(ImageResponseDtoToJSON)),
        'latitude': value['latitude'],
        'longitude': value['longitude'],
    };
}

