/* tslint:disable */
/* eslint-disable */
/**
 * 4차 프로젝트 6팀 March API
 * 6팀 March의 백엔드 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MessageSummary
 */
export interface MessageSummary {
    /**
     * 
     * @type {string}
     * @memberof MessageSummary
     */
    text?: string;
    /**
     * 
     * @type {Date}
     * @memberof MessageSummary
     */
    timestamp?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof MessageSummary
     */
    read?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MessageSummary
     */
    fromMe?: boolean;
}

/**
 * Check if a given object implements the MessageSummary interface.
 */
export function instanceOfMessageSummary(value: object): value is MessageSummary {
    return true;
}

export function MessageSummaryFromJSON(json: any): MessageSummary {
    return MessageSummaryFromJSONTyped(json, false);
}

export function MessageSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): MessageSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'] == null ? undefined : json['text'],
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
        'read': json['read'] == null ? undefined : json['read'],
        'fromMe': json['fromMe'] == null ? undefined : json['fromMe'],
    };
}

export function MessageSummaryToJSON(json: any): MessageSummary {
    return MessageSummaryToJSONTyped(json, false);
}

export function MessageSummaryToJSONTyped(value?: MessageSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
        'read': value['read'],
        'fromMe': value['fromMe'],
    };
}

