/* tslint:disable */
/* eslint-disable */
/**
 * 4차 프로젝트 6팀 March API
 * 6팀 March의 백엔드 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MemberModifyRequestDto } from './MemberModifyRequestDto';
import {
    MemberModifyRequestDtoFromJSON,
    MemberModifyRequestDtoFromJSONTyped,
    MemberModifyRequestDtoToJSON,
    MemberModifyRequestDtoToJSONTyped,
} from './MemberModifyRequestDto';
import type { UserKeywordSaveRequest } from './UserKeywordSaveRequest';
import {
    UserKeywordSaveRequestFromJSON,
    UserKeywordSaveRequestFromJSONTyped,
    UserKeywordSaveRequestToJSON,
    UserKeywordSaveRequestToJSONTyped,
} from './UserKeywordSaveRequest';

/**
 * 
 * @export
 * @interface ModifyMemberDto
 */
export interface ModifyMemberDto {
    /**
     * 
     * @type {MemberModifyRequestDto}
     * @memberof ModifyMemberDto
     */
    member?: MemberModifyRequestDto;
    /**
     * 
     * @type {Array<string>}
     * @memberof ModifyMemberDto
     */
    newImages?: Array<string>;
    /**
     * 
     * @type {Array<number>}
     * @memberof ModifyMemberDto
     */
    keepImageIds?: Array<number>;
    /**
     * 
     * @type {UserKeywordSaveRequest}
     * @memberof ModifyMemberDto
     */
    keywords?: UserKeywordSaveRequest;
}

/**
 * Check if a given object implements the ModifyMemberDto interface.
 */
export function instanceOfModifyMemberDto(value: object): value is ModifyMemberDto {
    return true;
}

export function ModifyMemberDtoFromJSON(json: any): ModifyMemberDto {
    return ModifyMemberDtoFromJSONTyped(json, false);
}

export function ModifyMemberDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModifyMemberDto {
    if (json == null) {
        return json;
    }
    return {
        
        'member': json['member'] == null ? undefined : MemberModifyRequestDtoFromJSON(json['member']),
        'newImages': json['newImages'] == null ? undefined : json['newImages'],
        'keepImageIds': json['keepImageIds'] == null ? undefined : json['keepImageIds'],
        'keywords': json['keywords'] == null ? undefined : UserKeywordSaveRequestFromJSON(json['keywords']),
    };
}

export function ModifyMemberDtoToJSON(json: any): ModifyMemberDto {
    return ModifyMemberDtoToJSONTyped(json, false);
}

export function ModifyMemberDtoToJSONTyped(value?: ModifyMemberDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'member': MemberModifyRequestDtoToJSON(value['member']),
        'newImages': value['newImages'],
        'keepImageIds': value['keepImageIds'],
        'keywords': UserKeywordSaveRequestToJSON(value['keywords']),
    };
}

