/* tslint:disable */
/* eslint-disable */
/**
 * 4차 프로젝트 6팀 March API
 * 6팀 March의 백엔드 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Sortnull } from './Sortnull';
import {
    SortnullFromJSON,
    SortnullFromJSONTyped,
    SortnullToJSON,
    SortnullToJSONTyped,
} from './Sortnull';

/**
 * 
 * @export
 * @interface Pageablenull
 */
export interface Pageablenull {
    /**
     * 
     * @type {boolean}
     * @memberof Pageablenull
     */
    paged?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Pageablenull
     */
    pageNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof Pageablenull
     */
    pageSize?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Pageablenull
     */
    unpaged?: boolean;
    /**
     * 
     * @type {number}
     * @memberof Pageablenull
     */
    offset?: number;
    /**
     * 
     * @type {Sortnull}
     * @memberof Pageablenull
     */
    sort?: Sortnull;
}

/**
 * Check if a given object implements the Pageablenull interface.
 */
export function instanceOfPageablenull(value: object): value is Pageablenull {
    return true;
}

export function PageablenullFromJSON(json: any): Pageablenull {
    return PageablenullFromJSONTyped(json, false);
}

export function PageablenullFromJSONTyped(json: any, ignoreDiscriminator: boolean): Pageablenull {
    if (json == null) {
        return json;
    }
    return {
        
        'paged': json['paged'] == null ? undefined : json['paged'],
        'pageNumber': json['pageNumber'] == null ? undefined : json['pageNumber'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'unpaged': json['unpaged'] == null ? undefined : json['unpaged'],
        'offset': json['offset'] == null ? undefined : json['offset'],
        'sort': json['sort'] == null ? undefined : SortnullFromJSON(json['sort']),
    };
}

export function PageablenullToJSON(json: any): Pageablenull {
    return PageablenullToJSONTyped(json, false);
}

export function PageablenullToJSONTyped(value?: Pageablenull | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'paged': value['paged'],
        'pageNumber': value['pageNumber'],
        'pageSize': value['pageSize'],
        'unpaged': value['unpaged'],
        'offset': value['offset'],
        'sort': SortnullToJSON(value['sort']),
    };
}

