/* tslint:disable */
/* eslint-disable */
/**
 * 4차 프로젝트 6팀 March API
 * 6팀 March의 백엔드 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChatRoomResponse } from './ChatRoomResponse';
import {
    ChatRoomResponseFromJSON,
    ChatRoomResponseFromJSONTyped,
    ChatRoomResponseToJSON,
    ChatRoomResponseToJSONTyped,
} from './ChatRoomResponse';
import type { Sortnull } from './Sortnull';
import {
    SortnullFromJSON,
    SortnullFromJSONTyped,
    SortnullToJSON,
    SortnullToJSONTyped,
} from './Sortnull';
import type { Pageablenull } from './Pageablenull';
import {
    PageablenullFromJSON,
    PageablenullFromJSONTyped,
    PageablenullToJSON,
    PageablenullToJSONTyped,
} from './Pageablenull';

/**
 * 
 * @export
 * @interface PageChatRoomResponse
 */
export interface PageChatRoomResponse {
    /**
     * 
     * @type {number}
     * @memberof PageChatRoomResponse
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageChatRoomResponse
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof PageChatRoomResponse
     */
    size?: number;
    /**
     * 
     * @type {Array<ChatRoomResponse>}
     * @memberof PageChatRoomResponse
     */
    content?: Array<ChatRoomResponse>;
    /**
     * 
     * @type {number}
     * @memberof PageChatRoomResponse
     */
    number?: number;
    /**
     * 
     * @type {Sortnull}
     * @memberof PageChatRoomResponse
     */
    sort?: Sortnull;
    /**
     * 
     * @type {number}
     * @memberof PageChatRoomResponse
     */
    numberOfElements?: number;
    /**
     * 
     * @type {Pageablenull}
     * @memberof PageChatRoomResponse
     */
    pageable?: Pageablenull;
    /**
     * 
     * @type {boolean}
     * @memberof PageChatRoomResponse
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageChatRoomResponse
     */
    last?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageChatRoomResponse
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the PageChatRoomResponse interface.
 */
export function instanceOfPageChatRoomResponse(value: object): value is PageChatRoomResponse {
    return true;
}

export function PageChatRoomResponseFromJSON(json: any): PageChatRoomResponse {
    return PageChatRoomResponseFromJSONTyped(json, false);
}

export function PageChatRoomResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageChatRoomResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'size': json['size'] == null ? undefined : json['size'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(ChatRoomResponseFromJSON)),
        'number': json['number'] == null ? undefined : json['number'],
        'sort': json['sort'] == null ? undefined : SortnullFromJSON(json['sort']),
        'numberOfElements': json['numberOfElements'] == null ? undefined : json['numberOfElements'],
        'pageable': json['pageable'] == null ? undefined : PageablenullFromJSON(json['pageable']),
        'first': json['first'] == null ? undefined : json['first'],
        'last': json['last'] == null ? undefined : json['last'],
        'empty': json['empty'] == null ? undefined : json['empty'],
    };
}

export function PageChatRoomResponseToJSON(json: any): PageChatRoomResponse {
    return PageChatRoomResponseToJSONTyped(json, false);
}

export function PageChatRoomResponseToJSONTyped(value?: PageChatRoomResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'size': value['size'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(ChatRoomResponseToJSON)),
        'number': value['number'],
        'sort': SortnullToJSON(value['sort']),
        'numberOfElements': value['numberOfElements'],
        'pageable': PageablenullToJSON(value['pageable']),
        'first': value['first'],
        'last': value['last'],
        'empty': value['empty'],
    };
}

