/* tslint:disable */
/* eslint-disable */
/**
 * 4차 프로젝트 6팀 March API
 * 6팀 March의 백엔드 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Sortnull } from './Sortnull';
import {
    SortnullFromJSON,
    SortnullFromJSONTyped,
    SortnullToJSON,
    SortnullToJSONTyped,
} from './Sortnull';
import type { AdminMemberDto } from './AdminMemberDto';
import {
    AdminMemberDtoFromJSON,
    AdminMemberDtoFromJSONTyped,
    AdminMemberDtoToJSON,
    AdminMemberDtoToJSONTyped,
} from './AdminMemberDto';
import type { Pageablenull } from './Pageablenull';
import {
    PageablenullFromJSON,
    PageablenullFromJSONTyped,
    PageablenullToJSON,
    PageablenullToJSONTyped,
} from './Pageablenull';

/**
 * 
 * @export
 * @interface PageAdminMemberDto
 */
export interface PageAdminMemberDto {
    /**
     * 
     * @type {number}
     * @memberof PageAdminMemberDto
     */
    totalElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageAdminMemberDto
     */
    totalPages?: number;
    /**
     * 
     * @type {Pageablenull}
     * @memberof PageAdminMemberDto
     */
    pageable?: Pageablenull;
    /**
     * 
     * @type {boolean}
     * @memberof PageAdminMemberDto
     */
    first?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PageAdminMemberDto
     */
    last?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PageAdminMemberDto
     */
    numberOfElements?: number;
    /**
     * 
     * @type {number}
     * @memberof PageAdminMemberDto
     */
    size?: number;
    /**
     * 
     * @type {Array<AdminMemberDto>}
     * @memberof PageAdminMemberDto
     */
    content?: Array<AdminMemberDto>;
    /**
     * 
     * @type {number}
     * @memberof PageAdminMemberDto
     */
    number?: number;
    /**
     * 
     * @type {Sortnull}
     * @memberof PageAdminMemberDto
     */
    sort?: Sortnull;
    /**
     * 
     * @type {boolean}
     * @memberof PageAdminMemberDto
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the PageAdminMemberDto interface.
 */
export function instanceOfPageAdminMemberDto(value: object): value is PageAdminMemberDto {
    return true;
}

export function PageAdminMemberDtoFromJSON(json: any): PageAdminMemberDto {
    return PageAdminMemberDtoFromJSONTyped(json, false);
}

export function PageAdminMemberDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageAdminMemberDto {
    if (json == null) {
        return json;
    }
    return {
        
        'totalElements': json['totalElements'] == null ? undefined : json['totalElements'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'pageable': json['pageable'] == null ? undefined : PageablenullFromJSON(json['pageable']),
        'first': json['first'] == null ? undefined : json['first'],
        'last': json['last'] == null ? undefined : json['last'],
        'numberOfElements': json['numberOfElements'] == null ? undefined : json['numberOfElements'],
        'size': json['size'] == null ? undefined : json['size'],
        'content': json['content'] == null ? undefined : ((json['content'] as Array<any>).map(AdminMemberDtoFromJSON)),
        'number': json['number'] == null ? undefined : json['number'],
        'sort': json['sort'] == null ? undefined : SortnullFromJSON(json['sort']),
        'empty': json['empty'] == null ? undefined : json['empty'],
    };
}

export function PageAdminMemberDtoToJSON(json: any): PageAdminMemberDto {
    return PageAdminMemberDtoToJSONTyped(json, false);
}

export function PageAdminMemberDtoToJSONTyped(value?: PageAdminMemberDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalElements': value['totalElements'],
        'totalPages': value['totalPages'],
        'pageable': PageablenullToJSON(value['pageable']),
        'first': value['first'],
        'last': value['last'],
        'numberOfElements': value['numberOfElements'],
        'size': value['size'],
        'content': value['content'] == null ? undefined : ((value['content'] as Array<any>).map(AdminMemberDtoToJSON)),
        'number': value['number'],
        'sort': SortnullToJSON(value['sort']),
        'empty': value['empty'],
    };
}

