/* tslint:disable */
/* eslint-disable */
/**
 * 4차 프로젝트 6팀 March API
 * 6팀 March의 백엔드 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProfileImageDto
 */
export interface ProfileImageDto {
    /**
     * 
     * @type {number}
     * @memberof ProfileImageDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ProfileImageDto
     */
    url?: string;
}

/**
 * Check if a given object implements the ProfileImageDto interface.
 */
export function instanceOfProfileImageDto(value: object): value is ProfileImageDto {
    return true;
}

export function ProfileImageDtoFromJSON(json: any): ProfileImageDto {
    return ProfileImageDtoFromJSONTyped(json, false);
}

export function ProfileImageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileImageDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function ProfileImageDtoToJSON(json: any): ProfileImageDto {
    return ProfileImageDtoToJSONTyped(json, false);
}

export function ProfileImageDtoToJSONTyped(value?: ProfileImageDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'url': value['url'],
    };
}

