/* tslint:disable */
/* eslint-disable */
/**
 * 4차 프로젝트 6팀 March API
 * 6팀 March의 백엔드 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserKeywordSaveRequest } from './UserKeywordSaveRequest';
import {
    UserKeywordSaveRequestFromJSON,
    UserKeywordSaveRequestFromJSONTyped,
    UserKeywordSaveRequestToJSON,
    UserKeywordSaveRequestToJSONTyped,
} from './UserKeywordSaveRequest';
import type { MemberRegisterRequestDto } from './MemberRegisterRequestDto';
import {
    MemberRegisterRequestDtoFromJSON,
    MemberRegisterRequestDtoFromJSONTyped,
    MemberRegisterRequestDtoToJSON,
    MemberRegisterRequestDtoToJSONTyped,
} from './MemberRegisterRequestDto';

/**
 * 
 * @export
 * @interface RegisterMemberRequest
 */
export interface RegisterMemberRequest {
    /**
     * 
     * @type {MemberRegisterRequestDto}
     * @memberof RegisterMemberRequest
     */
    member: MemberRegisterRequestDto;
    /**
     * 
     * @type {Array<Blob>}
     * @memberof RegisterMemberRequest
     */
    files?: Array<Blob>;
    /**
     * 
     * @type {UserKeywordSaveRequest}
     * @memberof RegisterMemberRequest
     */
    keywords: UserKeywordSaveRequest;
}

/**
 * Check if a given object implements the RegisterMemberRequest interface.
 */
export function instanceOfRegisterMemberRequest(value: object): value is RegisterMemberRequest {
    if (!('member' in value) || value['member'] === undefined) return false;
    if (!('keywords' in value) || value['keywords'] === undefined) return false;
    return true;
}

export function RegisterMemberRequestFromJSON(json: any): RegisterMemberRequest {
    return RegisterMemberRequestFromJSONTyped(json, false);
}

export function RegisterMemberRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterMemberRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'member': MemberRegisterRequestDtoFromJSON(json['member']),
        'files': json['files'] == null ? undefined : json['files'],
        'keywords': UserKeywordSaveRequestFromJSON(json['keywords']),
    };
}

export function RegisterMemberRequestToJSON(json: any): RegisterMemberRequest {
    return RegisterMemberRequestToJSONTyped(json, false);
}

export function RegisterMemberRequestToJSONTyped(value?: RegisterMemberRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'member': MemberRegisterRequestDtoToJSON(value['member']),
        'files': value['files'],
        'keywords': UserKeywordSaveRequestToJSON(value['keywords']),
    };
}

