/* tslint:disable */
/* eslint-disable */
/**
 * 4차 프로젝트 6팀 March API
 * 6팀 March의 백엔드 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserKeywordSaveRequest } from './UserKeywordSaveRequest';
import {
    UserKeywordSaveRequestFromJSON,
    UserKeywordSaveRequestFromJSONTyped,
    UserKeywordSaveRequestToJSON,
    UserKeywordSaveRequestToJSONTyped,
} from './UserKeywordSaveRequest';
import type { MemberRegisterRequestDto } from './MemberRegisterRequestDto';
import {
    MemberRegisterRequestDtoFromJSON,
    MemberRegisterRequestDtoFromJSONTyped,
    MemberRegisterRequestDtoToJSON,
    MemberRegisterRequestDtoToJSONTyped,
} from './MemberRegisterRequestDto';

/**
 * 
 * @export
 * @interface RegisterDTO
 */
export interface RegisterDTO {
    /**
     * 
     * @type {MemberRegisterRequestDto}
     * @memberof RegisterDTO
     */
    member?: MemberRegisterRequestDto;
    /**
     * 
     * @type {Array<string>}
     * @memberof RegisterDTO
     */
    files?: Array<string>;
    /**
     * 
     * @type {UserKeywordSaveRequest}
     * @memberof RegisterDTO
     */
    keywords?: UserKeywordSaveRequest;
}

/**
 * Check if a given object implements the RegisterDTO interface.
 */
export function instanceOfRegisterDTO(value: object): value is RegisterDTO {
    return true;
}

export function RegisterDTOFromJSON(json: any): RegisterDTO {
    return RegisterDTOFromJSONTyped(json, false);
}

export function RegisterDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'member': json['member'] == null ? undefined : MemberRegisterRequestDtoFromJSON(json['member']),
        'files': json['files'] == null ? undefined : json['files'],
        'keywords': json['keywords'] == null ? undefined : UserKeywordSaveRequestFromJSON(json['keywords']),
    };
}

export function RegisterDTOToJSON(json: any): RegisterDTO {
    return RegisterDTOToJSONTyped(json, false);
}

export function RegisterDTOToJSONTyped(value?: RegisterDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'member': MemberRegisterRequestDtoToJSON(value['member']),
        'files': value['files'],
        'keywords': UserKeywordSaveRequestToJSON(value['keywords']),
    };
}

