/* tslint:disable */
/* eslint-disable */
/**
 * 4차 프로젝트 6팀 March API
 * 6팀 March의 백엔드 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Sortnull
 */
export interface Sortnull {
    /**
     * 
     * @type {boolean}
     * @memberof Sortnull
     */
    empty?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Sortnull
     */
    sorted?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Sortnull
     */
    unsorted?: boolean;
}

/**
 * Check if a given object implements the Sortnull interface.
 */
export function instanceOfSortnull(value: object): value is Sortnull {
    return true;
}

export function SortnullFromJSON(json: any): Sortnull {
    return SortnullFromJSONTyped(json, false);
}

export function SortnullFromJSONTyped(json: any, ignoreDiscriminator: boolean): Sortnull {
    if (json == null) {
        return json;
    }
    return {
        
        'empty': json['empty'] == null ? undefined : json['empty'],
        'sorted': json['sorted'] == null ? undefined : json['sorted'],
        'unsorted': json['unsorted'] == null ? undefined : json['unsorted'],
    };
}

export function SortnullToJSON(json: any): Sortnull {
    return SortnullToJSONTyped(json, false);
}

export function SortnullToJSONTyped(value?: Sortnull | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'empty': value['empty'],
        'sorted': value['sorted'],
        'unsorted': value['unsorted'],
    };
}

