/* tslint:disable */
/* eslint-disable */
/**
 * 4차 프로젝트 6팀 March API
 * 6팀 March의 백엔드 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserKeywordSaveRequest
 */
export interface UserKeywordSaveRequest {
    /**
     * 
     * @type {Array<number>}
     * @memberof UserKeywordSaveRequest
     */
    keywordIds?: Array<number>;
}

/**
 * Check if a given object implements the UserKeywordSaveRequest interface.
 */
export function instanceOfUserKeywordSaveRequest(value: object): value is UserKeywordSaveRequest {
    return true;
}

export function UserKeywordSaveRequestFromJSON(json: any): UserKeywordSaveRequest {
    return UserKeywordSaveRequestFromJSONTyped(json, false);
}

export function UserKeywordSaveRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserKeywordSaveRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'keywordIds': json['keywordIds'] == null ? undefined : json['keywordIds'],
    };
}

export function UserKeywordSaveRequestToJSON(json: any): UserKeywordSaveRequest {
    return UserKeywordSaveRequestToJSONTyped(json, false);
}

export function UserKeywordSaveRequestToJSONTyped(value?: UserKeywordSaveRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'keywordIds': value['keywordIds'],
    };
}

