/* tslint:disable */
/* eslint-disable */
/**
 * 4차 프로젝트 6팀 March API
 * 6팀 March의 백엔드 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserKeywordResponse
 */
export interface UserKeywordResponse {
    /**
     * 
     * @type {number}
     * @memberof UserKeywordResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof UserKeywordResponse
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof UserKeywordResponse
     */
    categoryId?: number;
    /**
     * 
     * @type {string}
     * @memberof UserKeywordResponse
     */
    categoryName?: string;
}

/**
 * Check if a given object implements the UserKeywordResponse interface.
 */
export function instanceOfUserKeywordResponse(value: object): value is UserKeywordResponse {
    return true;
}

export function UserKeywordResponseFromJSON(json: any): UserKeywordResponse {
    return UserKeywordResponseFromJSONTyped(json, false);
}

export function UserKeywordResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserKeywordResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'categoryId': json['categoryId'] == null ? undefined : json['categoryId'],
        'categoryName': json['categoryName'] == null ? undefined : json['categoryName'],
    };
}

export function UserKeywordResponseToJSON(json: any): UserKeywordResponse {
    return UserKeywordResponseToJSONTyped(json, false);
}

export function UserKeywordResponseToJSONTyped(value?: UserKeywordResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'categoryId': value['categoryId'],
        'categoryName': value['categoryName'],
    };
}

