spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://localhost:3306/meeting_app?serverTimezone=Asia/Seoul
    username: root
    password: 3251
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: chat-group
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      fail-fast: false # KafkaAdmin 초기화 실패해도 앱 실행 계속

  redis:
    host: redis
    port: 6379

logging:
  level:
    org.apache.kafka: error # Kafka 관련 로그 너무 많을 때 INFO → ERROR
