/* tslint:disable */
/* eslint-disable */
/**
 * 4차 프로젝트 6팀 March API
 * 6팀 March의 백엔드 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GenericResponsePageChatRoomResponse,
  GenericResponseVoid,
} from '../models/index';
import {
    GenericResponsePageChatRoomResponseFromJSON,
    GenericResponsePageChatRoomResponseToJSON,
    GenericResponseVoidFromJSON,
    GenericResponseVoidToJSON,
} from '../models/index';

export interface DeleteChatroomRequest {
    otherMemberId: number;
}

export interface GetChatRoomsRequest {
    page?: number;
    size?: number;
}

/**
 * 
 */
export class ChatRoomControllerApi extends runtime.BaseAPI {

    /**
     */
    async deleteChatroomRaw(requestParameters: DeleteChatroomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenericResponseVoid>> {
        if (requestParameters['otherMemberId'] == null) {
            throw new runtime.RequiredError(
                'otherMemberId',
                'Required parameter "otherMemberId" was null or undefined when calling deleteChatroom().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['otherMemberId'] != null) {
            queryParameters['otherMemberId'] = requestParameters['otherMemberId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("kakaoOAuth", []);
        }

        const response = await this.request({
            path: `/api/chat/chatrooms/delete`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GenericResponseVoidFromJSON(jsonValue));
    }

    /**
     */
    async deleteChatroom(requestParameters: DeleteChatroomRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenericResponseVoid> {
        const response = await this.deleteChatroomRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getChatRoomsRaw(requestParameters: GetChatRoomsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenericResponsePageChatRoomResponse>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("kakaoOAuth", []);
        }

        const response = await this.request({
            path: `/api/chat/chatrooms`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GenericResponsePageChatRoomResponseFromJSON(jsonValue));
    }

    /**
     */
    async getChatRooms(requestParameters: GetChatRoomsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenericResponsePageChatRoomResponse> {
        const response = await this.getChatRoomsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
