/* tslint:disable */
/* eslint-disable */
/**
 * 4차 프로젝트 6팀 March API
 * 6팀 March의 백엔드 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GenericResponseBoolean,
  GenericResponseListMemberResponseDto,
  GenericResponseMemberRegisterResponseDto,
  GenericResponseMemberResponseDto,
  ModifyMemberDto,
  RegisterDTO,
} from '../models/index';
import {
    GenericResponseBooleanFromJSON,
    GenericResponseBooleanToJSON,
    GenericResponseListMemberResponseDtoFromJSON,
    GenericResponseListMemberResponseDtoToJSON,
    GenericResponseMemberRegisterResponseDtoFromJSON,
    GenericResponseMemberRegisterResponseDtoToJSON,
    GenericResponseMemberResponseDtoFromJSON,
    GenericResponseMemberResponseDtoToJSON,
    ModifyMemberDtoFromJSON,
    ModifyMemberDtoToJSON,
    RegisterDTOFromJSON,
    RegisterDTOToJSON,
} from '../models/index';

export interface CheckNicknameRequest {
    nickname: string;
}

export interface GetMemberProfileRequest {
    memberId: number;
}

export interface ModifyMemberInfoRequest {
    id: number;
    modifyMemberDto: ModifyMemberDto;
}

export interface RegisterRequest {
    registerDTO: RegisterDTO;
}

export interface SearchMembersByNicknameRequest {
    nickname: string;
}

export interface UpdateLocationRequest {
    memberId: number;
    latitude: number;
    longitude: number;
}

export interface WithdrawMemberRequest {
    memberId: number;
}

/**
 * 
 */
export class MemberControllerApi extends runtime.BaseAPI {

    /**
     */
    async checkNicknameRaw(requestParameters: CheckNicknameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenericResponseBoolean>> {
        if (requestParameters['nickname'] == null) {
            throw new runtime.RequiredError(
                'nickname',
                'Required parameter "nickname" was null or undefined when calling checkNickname().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['nickname'] != null) {
            queryParameters['nickname'] = requestParameters['nickname'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("kakaoOAuth", []);
        }

        const response = await this.request({
            path: `/api/members/checkNickname`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GenericResponseBooleanFromJSON(jsonValue));
    }

    /**
     */
    async checkNickname(requestParameters: CheckNicknameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenericResponseBoolean> {
        const response = await this.checkNicknameRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getMemberProfileRaw(requestParameters: GetMemberProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenericResponseMemberResponseDto>> {
        if (requestParameters['memberId'] == null) {
            throw new runtime.RequiredError(
                'memberId',
                'Required parameter "memberId" was null or undefined when calling getMemberProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("kakaoOAuth", []);
        }

        const response = await this.request({
            path: `/api/members/{memberId}`.replace(`{${"memberId"}}`, encodeURIComponent(String(requestParameters['memberId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GenericResponseMemberResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async getMemberProfile(requestParameters: GetMemberProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenericResponseMemberResponseDto> {
        const response = await this.getMemberProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getMyProfileRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenericResponseMemberResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("kakaoOAuth", []);
        }

        const response = await this.request({
            path: `/api/members/me`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GenericResponseMemberResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async getMyProfile(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenericResponseMemberResponseDto> {
        const response = await this.getMyProfileRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async modifyMemberInfoRaw(requestParameters: ModifyMemberInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenericResponseMemberResponseDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling modifyMemberInfo().'
            );
        }

        if (requestParameters['modifyMemberDto'] == null) {
            throw new runtime.RequiredError(
                'modifyMemberDto',
                'Required parameter "modifyMemberDto" was null or undefined when calling modifyMemberInfo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("kakaoOAuth", []);
        }

        const response = await this.request({
            path: `/api/members/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ModifyMemberDtoToJSON(requestParameters['modifyMemberDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GenericResponseMemberResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async modifyMemberInfo(requestParameters: ModifyMemberInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenericResponseMemberResponseDto> {
        const response = await this.modifyMemberInfoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async registerRaw(requestParameters: RegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenericResponseMemberRegisterResponseDto>> {
        if (requestParameters['registerDTO'] == null) {
            throw new runtime.RequiredError(
                'registerDTO',
                'Required parameter "registerDTO" was null or undefined when calling register().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("kakaoOAuth", []);
        }

        const response = await this.request({
            path: `/api/members/register`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterDTOToJSON(requestParameters['registerDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GenericResponseMemberRegisterResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async register(requestParameters: RegisterRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenericResponseMemberRegisterResponseDto> {
        const response = await this.registerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async searchMembersByNicknameRaw(requestParameters: SearchMembersByNicknameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenericResponseListMemberResponseDto>> {
        if (requestParameters['nickname'] == null) {
            throw new runtime.RequiredError(
                'nickname',
                'Required parameter "nickname" was null or undefined when calling searchMembersByNickname().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['nickname'] != null) {
            queryParameters['nickname'] = requestParameters['nickname'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("kakaoOAuth", []);
        }

        const response = await this.request({
            path: `/api/members/search`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GenericResponseListMemberResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async searchMembersByNickname(requestParameters: SearchMembersByNicknameRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenericResponseListMemberResponseDto> {
        const response = await this.searchMembersByNicknameRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateLocationRaw(requestParameters: UpdateLocationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenericResponseMemberResponseDto>> {
        if (requestParameters['memberId'] == null) {
            throw new runtime.RequiredError(
                'memberId',
                'Required parameter "memberId" was null or undefined when calling updateLocation().'
            );
        }

        if (requestParameters['latitude'] == null) {
            throw new runtime.RequiredError(
                'latitude',
                'Required parameter "latitude" was null or undefined when calling updateLocation().'
            );
        }

        if (requestParameters['longitude'] == null) {
            throw new runtime.RequiredError(
                'longitude',
                'Required parameter "longitude" was null or undefined when calling updateLocation().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['latitude'] != null) {
            queryParameters['latitude'] = requestParameters['latitude'];
        }

        if (requestParameters['longitude'] != null) {
            queryParameters['longitude'] = requestParameters['longitude'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("kakaoOAuth", []);
        }

        const response = await this.request({
            path: `/api/members/{memberId}/location`.replace(`{${"memberId"}}`, encodeURIComponent(String(requestParameters['memberId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GenericResponseMemberResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async updateLocation(requestParameters: UpdateLocationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenericResponseMemberResponseDto> {
        const response = await this.updateLocationRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async withdrawMemberRaw(requestParameters: WithdrawMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenericResponseMemberResponseDto>> {
        if (requestParameters['memberId'] == null) {
            throw new runtime.RequiredError(
                'memberId',
                'Required parameter "memberId" was null or undefined when calling withdrawMember().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("kakaoOAuth", []);
        }

        const response = await this.request({
            path: `/api/members/{memberId}`.replace(`{${"memberId"}}`, encodeURIComponent(String(requestParameters['memberId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GenericResponseMemberResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async withdrawMember(requestParameters: WithdrawMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenericResponseMemberResponseDto> {
        const response = await this.withdrawMemberRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
