/* tslint:disable */
/* eslint-disable */
/**
 * 4차 프로젝트 6팀 March API
 * 6팀 March의 백엔드 API 명세서입니다.
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GenericResponseListRecommendedUserDto,
} from '../models/index';
import {
    GenericResponseListRecommendedUserDtoFromJSON,
    GenericResponseListRecommendedUserDtoToJSON,
} from '../models/index';

/**
 * 
 */
export class UserRecommendationControllerApi extends runtime.BaseAPI {

    /**
     */
    async dailyRecommendRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenericResponseListRecommendedUserDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("kakaoOAuth", []);
        }

        const response = await this.request({
            path: `/api/matching/daily-recommend`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GenericResponseListRecommendedUserDtoFromJSON(jsonValue));
    }

    /**
     */
    async dailyRecommend(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenericResponseListRecommendedUserDto> {
        const response = await this.dailyRecommendRaw(initOverrides);
        return await response.value();
    }

}
