-- -- 유저 (ID = 1)
-- INSERT INTO member (id, kakao_id, email, nickname, age, height, gender,
--                     chat_able, latitude, longitude,
--                     kakao_access_token, kakao_refresh_token, is_deleted
-- )
-- VALUES (
--         1, 100001, 'blocker@example.com', '차단자유저', 25, 170, 'MALE',
--         true, 37.123456, 127.654321,
--         'access_token_1', 'refresh_token_1', false
-- );
--
-- --유저 (ID = 2)
-- INSERT INTO member (id, kakao_id, email, nickname, age, height, gender,
--                     chat_able, latitude, longitude,
--                     kakao_access_token, kakao_refresh_token, is_deleted
-- )
-- VALUES (
--            2, 100002, 'blocked@example.com', '차단대상유저', 23, 165, 'FEMALE',
--            true, 37.987654, 127.123456,
--            'access_token_2', 'refresh_token_2', false
--        );
--
--
