name: Build Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        working-directory: ./WEB3_4_MARCH_BE
        run: chmod +x ./gradlew

      - name: Build with Gradle
        working-directory: ./WEB3_4_MARCH_BE
        run: ./gradlew clean build
